### PR TITLE
native pointers for each type

### LINKED ISSUE #90: Native pointers
Introduce functions for each object type that enables the user to get the native pointers of underlying types. This allows users to integrate with libraries that expect native pointers. Users can then use llri::getImplementation() to cast the resulted pointers to the correct types.

### PR DESCRIPTION
**Pull request by LeonBrands**
Closes #90

### CODE REVIEW

**Comment by GlynLeine** [comment]
I think this might be a good pr to mention this in. The pr looks good as is. But i was thinking that maybe for the same of semantics it might be nicer to use type aliases for void pointers like:
```cpp
using native_device = void;

...

native_device* m_ptr;
```

**Comment by LeonBrands** [comment]
> I think this might be a good pr to mention this in. The pr looks good as is. But i was thinking that maybe for the same of semantics it might be nicer to use type aliases for void pointers like:
> 
> ```c++
> using native_device = void;
> 
> ...
> 
> native_device* m_ptr;
> ```

Hmm, what if we did this inside of the scope of the class? e.g. `llri::Device::native_ptr` or something along those lines? (naming still very much up for discussion)

**Comment by GlynLeine** [comment]
> > I think this might be a good pr to mention this in. The pr looks good as is. But i was thinking that maybe for the same of semantics it might be nicer to use type aliases for void pointers like:
> > ```c++
> > using native_device = void;
> > 
> > ...
> > 
> > native_device* m_ptr;
> > ```
> 
> Hmm, what if we did this inside of the scope of the class? e.g. `llri::Device::native_ptr` or something along those lines? (naming still very much up for discussion)

I'd say that's up to you, whichever you prefer. but just any type alias already communicates way more than just void*

**Comment by LeonBrands** [comment]
Alright, I'll change to that then

**Review by GlynLeine — APPROVED** [review]

**Pull request merged**
